### ISSUE TITLE
Couldn't get lyrics. Having problem with Jetbrains Toolbox

### ISSUE THREAD

**Issue by erkantaylan** [SwagLyrics/SwagLyricsGUI#10]
I have JetBrains Toolbox installed too but I don't know why it is related.

![error](https://user-images.githubusercontent.com/5616631/100314715-2c109a80-2faf-11eb-98d7-57ccccede773.png)

Before this I application did not open at all after install. I checked Event Viewer and found out that I needed admin privileges. I re-run installer as admin and applicatin now starts but gives this error thingy.

```Application: SwagLyricsGUI.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\SwagLyricsGUI\nmoexge3.tmp' is denied. (C:\Program Files (x86)\SwagLyricsGUI\SwagLyricsGUI.dll.config)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SwagLyricsGUI\nmoexge3.tmp' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.Internal.TempFileCollection.EnsureTempNameCreated()
   at System.IO.Internal.TempFileCollection.get_BasePath()
   at System.IO.Internal.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at System.IO.Internal.TempFileCollection.AddExtension(String fileExtension)
   at System.Configuration.Internal.WriteFileContext..ctor(String filename, String templateFilename)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.ClientConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.UpdateConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.Internal.DelegatingConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll)
   at System.Configuration.Configuration.Save()
   at SwagLyricsGUI.ViewModels.MainWindowViewModel.set_ThemeIndex(Int32 value)
   at SwagLyricsGUI.ViewModels.MainWindowViewModel..ctor()
   at SwagLyricsGUI.App.OnFrameworkInitializationCompleted()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SwagLyricsGUI.Program.Main(String[] args)
```

Windows 10 OS Build 19041.630

**Comment by erkantaylan** [comment]
Interesting thing is if I close Jetbrains Toolbox it works and stops working when I open back.

**Comment by aadibajpai** [comment]
@flabbet what do you think this could be? SwSpotify mistaking Jetbrains Toolbox window title to be a Spotify title? Not sure why admin privs are required tho

**Comment by erkantaylan** [comment]
Should I move issue to SwSpotify?

**Comment by aadibajpai** [comment]
> Should I move issue to SwSpotify?

I'll move it once we know what's up with the admin issue. The Jetbrains part is more suitable there
